[compiler.solc]
# Disable Wake diagnostics
allow_paths = []
include_paths = []
remappings = []

[lsp]
# Disable LSP diagnostics
diagnostics = false
code_lens = false
hover = false

[detectors]
# Disable all detectors to remove warnings
exclude = [".*"]

[printers]
# Disable all printers
exclude = [".*"]